# this is an example of the Crime API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: CrimeNet API
  description: More em locais seguros com o CrimeNet API
  version: "1.0.0"
# the domain of the service
host: api.crimenet.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /localidades:
    get:
      summary: Locais ordenados por nº de ocorrências.
      description: |
        Este atributo retorna informação sobre as diversas localidades pesquisadas e as ordena
        de acordo com o nº de ocorrências ao seu redor. Tiers de classificação (S, A, B, C e D) são
        atribuídos a essas localidades, sendo S locais com excelente segurança e D áreas completamente inabitáveis.
      parameters:
        - name: tier
          in: query
          description: O tier da localidade.
          required: true
          type: string
          
        - name: nº de ocorrências
          in: query
          description: O número de ocorrências registradas ao redor da localidade.
          required: true
          type: number
          format: double
        - name: ocorrências recentes
          in: query
          description: As últimas ocorrências registradas ao redor da localidade.
          required: true
          type: string
            
      tags:
        - Local
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /sujeitos:
    get:
      summary: Relação de ex-detentos com moradia registrada ao redor da localidade em questão.
      description: |
        Mostrará ex-detentos que cumpriram pena por crimes de violência que residem na área.
      parameters:
        - name: Endereço
          in: query
          description: Endereço da pessoa.
          required: true
          type: string
          
        - name: Crime
          in: query
          description: Crime ao qual a pessoa foi condenada.
          required: true
          type: string
          
        - name: Reincidênte
          in: query
          description: Se a pessoa é reincidente ou não.
          required: true
          type: boolean
          
        - name: Taxa de reincidência
          in: query
          description: Se a pessoa for reincidente, esta estatistíca dirá a taxa.
          required: true
          type: number
          format: double
      tags:
        - Perfis
      responses:
        200:
          description: An array of price estimates by product
          schema:
            type: array
            items:
              $ref: '#/definitions/PriceEstimate'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /delegacias:
    get:
      summary: Delegacias
      description: Detalha que delegacias estão disponíveis nos arredores
      parameters:
        - name: Endereço
          in: query
          description: Endereço da delegacia.
          required: true
          type: string
          
        - name: Distância
          in: query
          description: Distância da delegacia a partir de um ponto especificado pelo usuário.
          required: true
          type: number
          format: double
        
      tags:
        - Pontos de Interesse
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Activities'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /usuario:
    get:
      summary: Perfil de usuário
      description: Perfil de usuário para fazer críticas quanto a segurança da localidade. Serve como medida para clientes buscando dados mais abstratos do que apenas números.
      parameters:
        - name: Nome
          in: query
          description: Nome do usuário.
          required: true
          type: string
        - name: Endereço
          in: query
          description: Endereço do usuário.
          required: true
          type: string
      tags:
        - Usuário
      responses:
        200:
          description: Profile information for a user
          schema:
            $ref: '#/definitions/Profile'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
definitions:
  Product:
    type: object
    properties:
      product_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      description:
        type: string
        description: Description of product.
      display_name:
        type: string
        description: Display name of product.
      capacity:
        type: string
        description: Capacity of product. For example, 4 people.
      image:
        type: string
        description: Image URL representing the product.
  PriceEstimate:
    type: object
    properties:
      product_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles
      currency_code:
        type: string
        description: "[ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code."
      display_name:
        type: string
        description: Display name of product.
      estimate:
        type: string
        description: Formatted string of estimate in local currency of the start location. Estimate could be a range, a single number (flat rate) or "Metered" for TAXI.
      low_estimate:
        type: number
        description: Lower bound of the estimated price.
      high_estimate:
        type: number
        description: Upper bound of the estimated price.
      surge_multiplier:
        type: number
        description: Expected surge multiplier. Surge is active if surge_multiplier is greater than 1. Price estimate already factors in the surge multiplier.
  Profile:
    type: object
    properties:
      first_name:
        type: string
        description: First name of the Uber user.
      last_name:
        type: string
        description: Last name of the Uber user.
      email:
        type: string
        description: Email address of the Uber user
      picture:
        type: string
        description: Image URL of the Uber user.
      promo_code:
        type: string
        description: Promo code of the Uber user.
  Activity:
    type: object
    properties:
      uuid:
        type: string
        description: Unique identifier for the activity
  Activities:
    type: object
    properties:
      offset:
        type: integer
        format: int32
        description: Position in pagination.
      limit:
        type: integer
        format: int32
        description: Number of items to retrieve (100 max).
      count:
        type: integer
        format: int32
        description: Total number of items available.
      history:
        type: array
        items:
          $ref: '#/definitions/Activity'
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
